2b2t: true
50beardsofgrey: true
690squadron: true
abortopedia: true
acqint: true
adlc: true
adnovum: true
aeross: true
afterworld: true
agilebook: true
air: true
aisg: true
aktpos: true
alanoccv: true
ale: true
algopedia: true
allthetropes: 'allthetropes.org'
allwikis: true
alternatehistory: true
alternatesporthistory: true
altuspoliticsproject: true
altverse: true
alwiki: true
amazingyoutubers: true
ancyclopedia: true
andusan: true
aniwotawiki: true
apcwiki: 'www.apcwiki.org'
apneuvereniging: true
apuntes: true
archiwumsportowe: true
arefepva: true
arphilosophy: true
artificercreations: true
ar: true
asgyaanipedia: true
astrobiology: 'encyclopediaofastrobiology.org'
atlasinternational: true
atm: true
atrociousdeviants: true
atrociousyoutubers: true
attackontitan: true
australiasim: true
awesomegames: true
awfulmovies: true
ayrshire: true
ayurbooks: true
balcanopediascharlatanica: true
bch: true
bearwiki: true
beremagne: true
besttvshows: true
betapurple: true
bgo: true
biblicalwiki: true
bigforest: true
bildung: true
biu: true
blepia: true
blocknet: true
bloowiki: true
bngyaanipedia: 'bn.gyaanipedia.co.in'
bogdan: true
bonessdiving: 'wiki.bonessdiving.club'
bonziworld: true
borost: true
bpa: true
breedersofthenephelym: true
brynda1231: true
bst: true
bunker401: true
bus: true
byblopedia: true
caestaron: true
calibro: true
cantorij: true
carmeigat: true
cartesium: true
casuarina: true
cbhssjb: true
cccp: true
cdc: true
central: true
changemyorg: true
chimaera: true
christipedia: true
civclassic: true
civitas: true
ckc: true
clonedeploy: true
cloudconstruct: true
cmhoc: true
cnv: true
codexamica: true
commonsgyaanipedia: 'commons.gyaanipedia.co.in'
commonswiki: true
communitydirectedsupport: true
concepts: true
const: true
corepedia: true
corsarius: true
corydoctorow: true
cpdiscordedition: true
crappygames: true
crazybloxianempireinfo: true
credco: true
csnimsbordeaux: true
cyberlaw: true
dakhilcommunity: true
dalar: true
decrypted: 'decrypted.wiki'
destinos: true
diaroleplays: true
didapro: 'encyclopedie.didactiqueprofessionnelle.org'
differenthistory: true
discovereachother: true
dish: true
dobots: 'wiki.dobots.nl'
doin: true
doomsdaydebunked: true
dragpedia: 'drag.lgbt'
drones4all: 'wiki.drones4nature.info'
dwe: true
dwplive: 'wiki.dwplive.com'
dyrn: true
eaddemos: true
earthian: true
ecoepi: true
edmund: true
edustudent: true
edw: true
eerstelijnszones: 'www.eerstelijnszones.be'
electowiki: 'electowiki.org'
ellersliedemo: true
elpoderdelpueblo: true
encyclopedia: true
enigma: true
environmentaljustice: true
eon: true
epicerieissy: true
epicseven: true
espiral: 'espiral.org'
eva: true
exocortex: 'exocortex.sillyendpoints.com'
eyebobs: true
fantasia: true
ferahistoria: true
feu: 'froggy.info'
fgnotes: true
fictionfoundry: true
fifam: true
fikcyjnatv: 'fikcyjnatv.pl'
fkkfan: true
fluxordev: true
fmbv: true
fna: true
foodsharinghamburg: true
forbidden: true
fortnite: true
freestateofjones: true
freevandalism: true
frejaeriksson: true
frontdesks: true
fsxworldspain: true
futurewiki: true
garrettcountyguide: 'garrettcountyguide.com'
gasepedia: true
geirpedia: true
generationsbamoro: true
gen: true
geometrydash: true
gepacoassoculture: true
gepacobiodiv: true
geresbamyan: true
gfi: true
ghhs: true
gkatom: true
glueckssammler: true
godottuts: true
gontran: true
grandtheftauto: true
graymainewiki: true
grdarchive: true
greatcharacterswiki: true
greatestmovies: true
gsb: true
gtnh: true
gua: true
guiaslocais: 'guiasdobrasil.com.br'
guidefrance: true
gyaanipedia: 'en.gyaanipedia.co.in'
gze: true
hamfem: true
harrypotter: true
haxballportugal: true
healthvector: true
hgwiki: 'hgwiki.ga'
hiawa: true
higyaanipedia: 'hi.gyaanipedia.co.in'
hirondepedia: true
hjelpemidler: true
hkimgboard: true
hobbies: true
holonet: 'holonet.pw'
horizon: true
icmscholars: true
idolmaster: true
idw: true
ilasoram: true
imaginarypedia: true
imagine: true
inazumaeleven: true
incorrecttohowiki: true
indiasim: true
indrik: true
infectoped: 'infectowiki.com'
info: true
innovwikiproto: true
intrabase: true
ipedia: true
ipoly: true
isv: true
itspugle: true
iubris: true
iwn: true
izanagi: true
jalproverse: true
jawptest: true
jcs: 'wiki.gesamtschule-nordkirchen.de'
jeong000307: true
jeongi: true
jordepedia: true
joustro: 'wiki.joust.ro'
jrichard: true
justinbieber: true
jwiki: true
jwwiki: true
kai: true
kapuluan: true
karniaruthenia: true
kasopedia: true
kassai: true
kbrproject: true
kerbalism: true
kgb: true
kinderacic: true
kkutu: 'kkutu.wiki'
klimagruppe: true
kngyaanipedia: 'kn.gyaanipedia.co.in'
knowledgebox: true
knowledge: true
kosatsuwiki: true
krebs: true
kstartups: 'wiki.besuccess.com'
kurwowizja: true
kybermc: 'wiki.kybermc.tk'
lambdawars: true
lapolitics: true
lastcrew: true
lawrencescafuri: true
legina: true
lexwiki: true
limpd: true
limzhihaowinston: true
lingnlang: true
lionhearttales: true
livingdeadman: true
loathsomecharacters: true
loolomis: true
lovelive: true
lunfeng: true
lzhscpwiki: true
m00se: true
maccnyc: 'wiki.macc.nyc'
magez: true
magnaverse: true
maiasongcontest: true
make717: 'wiki.make717.org'
maktaba: true
malaysia: 'www.mywiki.icu'
mamsprawdzone: true
marinebiodiversitymatrix: 'marinebiodiversitymatrix.org'
marioserieswiki: true
marthaspeaks: true
masseffect: true
mattsworldbuilding: true
medergists: true
mediateca: true
medicina: true
meregos: 'meregos.com'
meta: true
metrocraft: true
mgyaanipedia: 'mg.gyaanipedia.co.in'
microtonal: true
mikeandchrisproductions: true
mikipedia: true
mikrodev: 'wiki.mikrodev.com'
miningpromies: true
mnzp: true
modelshipreference: true
modesofdiscourse: 'www.modesofdiscourse.com'
modular: true
monarchists: 'monarchists.wiki'
mrgyaanipedia: 'mr.gyaanipedia.co.in'
mundoparalelo: true
musicarchive: true
n2go: true
nanatsunotaizai: true
nano: true
naod: true
nationsglory: true
navmed: true
ndg: 'ndg.nenawiki.org'
nenawiki: 'nenawiki.org'
nerdzone: true
netazar: 'www.netazar.org'
netspace: true
newarkmanor: true
newknowledge: true
newsnow: 'newsnow.wiki'
nextlevelwiki: 'wiki.lbcomms.co.za'
nexusaeternia: true
nimrodnero: true
noalatala: true
nonbinary: 'nonbinary.wiki'
nonciclopedia: 'nonciclopedia.org'
norskrap: true
northhub: true
notasdeproducao: true
novaya: true
novelists: true
nrp1: true
nutrition: true
nvc: true
nvliu: true
nxwiki: true
nychousingwiki: true
oecumene: 'oecumene.org'
ofthevampire: true
omnis: true
oncproject: true
opengovpioneers: true
openpolicy: true
opmi: true
oryza: true
ourmeta: true
ourmxfest: true
ourpediajp: true
ourrail: true
oursource: true
ourwiki: true
overon: true
pactrack: true
pagyaanipedia: 'pa.gyaanipedia.co.in'
paliwiki: true
pam: true
pandorauniverse: true
paodeaoda: true
parents: true
paulsec: true
pb2stof: true
pbg: true
pcarchitect: 'pc-architect.tk'
pcbs: true
peace: true
perfume: 'prfm.wiki'
permanentfuturelab: 'permanentfuturelab.wiki'
perrexipedia: true
perthowiki: true
petctviewer: true
petersburg: true
pfsolutions: true
physics: true
plasticssongcontest: true
plazmaburst: true
plnonbinary: 'pl.nonbinary.wiki'
pmav: true
podpedia: 'podpedia.org'
popnmusic: true
privado: true
priyo: true
prnet: 'wiki.pablojprieto.com.es'
programario: true
projectsoundicate: true
prueba: 'es.publictestwiki.com'
psiconauta: 'psiconauta.pt'
pushups: true
puzzle: true
pwiki: 'pwiki.arkcls.com'
pythia: true
r2: true
rakudaikishi: true
rasamruta: true
raspberry: true
rawdata: true
renaissance: true
revit: true
rigpaparis: true
rodcs: true
rollerderbylille: true
rontgenwiki: true
rootsandlimbs: true
rottenwebsites: true
rseifv: true
rs: true
rwdvolvo: true
rwsales: true
safiria: true
saharinspace: true
sainsterbuka: true
saoirsewiki: true
sapiens: true
savagewiki: 'savage-wiki.com'
sawiki: true
schattenvonskelos: true
schicksalswiki: true
schul: 'www.schulwiki.de'
scouts: 'wiki.doverdistrictscouts.co.uk'
scruffy: true
sdiy: 'sdiy.info'
seldir: true
senpaga: true
serinfhosp: true
sharingcv: true
shingekinokyojin: true
shippingandmeta: true
shortwiki: true
showmedicina: true
shroudedpath: true
sidem: true
sirikot: true
skgy: true
snowthegame: true
socioatlas: true
socrates: true
sofw: true
songcontests: true
southparkfan: true
spevt: true
spiral: 'spiral.wiki'
spritopia: true
ssmc: true
sss: true
stablestate: 'stablestate.org'
staff: true
statistics: true
stellachronica: true
stella: true
sthomaspri: true
stjarnfestivalen: true
studentwiki: 'studentwiki.ddns.net'
sudzerbal: true
summerolympics: true
svenskabriardklubben: 'wiki.svenskabriardklubben.se'
sv: true
tag: true
tagyaanipedia: 'ta.gyaanipedia.co.in'
takethatwiki: true
taller: true
tavernia: true
taylantatli: true
techwiki: 'wiki.pupilliam.com'
tegyaanipedia: 'te.gyaanipedia.co.in'
tekken: true
template: true
tenebris: true
teria: true
terribletvshows: true
tesminadventures: true
test1: true
test: 'publictestwiki.com'
thecsc: true
thehearth: true
thehushhushsaga: true
theresnothingbetter: true
thesciencearchives: true
theworld: true
titania: true
tkchpedia: true
tme: true
tnotes: true
tocgamingproject: true
toitumine: true
toms: true
torejorg: true
trablang: true
trex: true
triseptsolutions: true
trollpedia: true
trwc: true
ttinfo: true
twtrain: true
ubrwiki: true
ucronias: true
universepedia: true
unmusicfest: true
untrash: true
uolu: true
usse: true
utamacross: true
uzenc: 'enc.for.uz'
valentinaproject: 'wiki.valentinaproject.org'
valentinawiki: true
vandalismwiki: true
viagroupia: true
vicproject: true
victorianrp: true
vilemaxim: true
volleyball: true
voting: true
vtr: true
wabc: true
warapedia: true
warewiki: true
warframe: 'wiki.warfra.ml'
web: true
westparrot: true
wikiageing: true
wikibook: true
wikidespacito: true
wikiescola: 'wikiescola.com.br'
wikifinanza: true
wikimedici: true
wikipuc: 'wikipuk.cl'
wikitranslate: 'wikitranslate.tk'
wisdomwiki: 'wisdomwiki.org'
wish: true
worldvisionsongcontest: true
wrl: true
xdjibi: true
xenharmonic: true
xxcircle: true
yacresources: true
yanderedev: true
ylsc: true
yourbuddy: true
yourosongcontest: true
zendari: true
zero: true
zitabites: true